-- The Windows accessibility-related settings of a recording, on the
-- system.preferences channel: every setting at the start and stop
-- (windows-preferences), and each change of one setting with its reading
-- before and after and the notice that led to the reading
-- (windows-preference-changed). Each setting is stored as its value, by the
-- setting's type, and the problem that stopped its reading; the monitors,
-- with their scale, in a child table. The evidence tables are not written
-- for a recording that has a recording file (see 0013_recording_files.sql);
-- they keep mapping every payload member so the database writer still
-- accepts every record. See docs/architecture/accessibility-preferences.md.
--
-- Each table is made as 0009_unpartitioned_recording_tables.sql left the
-- other per-recording tables: an ordinary table keyed by recording and
-- event, whose references are listed in recording_references and checked
-- when the recording is completed, as since 0011_bulk_reference_checks.sql,
-- and not by a foreign key.

CREATE TABLE windows_preference_snapshots (
    recording_id uuid NOT NULL,
    event_key bigint NOT NULL,
    reason_name_id integer NOT NULL,
    ui_settings_events_advanced_effects_enabled_changed boolean NOT NULL,
    ui_settings_events_animations_enabled_changed boolean NOT NULL,
    ui_settings_events_auto_hide_scroll_bars_changed boolean NOT NULL,
    ui_settings_events_text_scale_factor_changed boolean NOT NULL,
    ui_settings_events_color_values_changed boolean NOT NULL,
    has_settings_monitors_value boolean NOT NULL,
    settings_monitors_problem text,
    settings_text_scale_factor_value double precision,
    settings_text_scale_factor_problem text,
    settings_apps_use_light_theme_value boolean,
    settings_apps_use_light_theme_problem text,
    settings_transparency_effects_value boolean,
    settings_transparency_effects_problem text,
    settings_color_filter_active_value boolean,
    settings_color_filter_active_problem text,
    settings_color_filter_type_value bigint,
    settings_color_filter_type_problem text,
    settings_high_contrast_value boolean,
    settings_high_contrast_problem text,
    settings_high_contrast_scheme_value text,
    settings_high_contrast_scheme_problem text,
    settings_accent_color_value text,
    settings_accent_color_problem text,
    settings_animations_enabled_value boolean,
    settings_animations_enabled_problem text,
    settings_ui_effects_value boolean,
    settings_ui_effects_problem text,
    settings_menu_animation_value boolean,
    settings_menu_animation_problem text,
    settings_menu_fade_value boolean,
    settings_menu_fade_problem text,
    settings_combo_box_animation_value boolean,
    settings_combo_box_animation_problem text,
    settings_cursor_width_value double precision,
    settings_cursor_width_problem text,
    settings_cursor_height_value double precision,
    settings_cursor_height_problem text,
    settings_caret_width_value bigint,
    settings_caret_width_problem text,
    settings_caret_blink_time_value bigint,
    settings_caret_blink_time_problem text,
    settings_focus_border_width_value bigint,
    settings_focus_border_width_problem text,
    settings_focus_border_height_value bigint,
    settings_focus_border_height_problem text,
    settings_keyboard_cues_value boolean,
    settings_keyboard_cues_problem text,
    settings_auto_hide_scroll_bars_value boolean,
    settings_auto_hide_scroll_bars_problem text,
    settings_message_duration_value bigint,
    settings_message_duration_problem text,
    settings_sticky_keys_value boolean,
    settings_sticky_keys_problem text,
    settings_filter_keys_value boolean,
    settings_filter_keys_problem text,
    settings_toggle_keys_value boolean,
    settings_toggle_keys_problem text,
    settings_mouse_keys_value boolean,
    settings_mouse_keys_problem text,
    PRIMARY KEY (recording_id, event_key)
);

CREATE TABLE windows_preference_changes (
    recording_id uuid NOT NULL,
    event_key bigint NOT NULL,
    setting_name_id integer NOT NULL,
    has_previous_monitors boolean NOT NULL,
    has_previous_monitors_value boolean,
    previous_monitors_problem text,
    has_previous_text_scale_factor boolean NOT NULL,
    previous_text_scale_factor_value double precision,
    previous_text_scale_factor_problem text,
    has_previous_apps_use_light_theme boolean NOT NULL,
    previous_apps_use_light_theme_value boolean,
    previous_apps_use_light_theme_problem text,
    has_previous_transparency_effects boolean NOT NULL,
    previous_transparency_effects_value boolean,
    previous_transparency_effects_problem text,
    has_previous_color_filter_active boolean NOT NULL,
    previous_color_filter_active_value boolean,
    previous_color_filter_active_problem text,
    has_previous_color_filter_type boolean NOT NULL,
    previous_color_filter_type_value bigint,
    previous_color_filter_type_problem text,
    has_previous_high_contrast boolean NOT NULL,
    previous_high_contrast_value boolean,
    previous_high_contrast_problem text,
    has_previous_high_contrast_scheme boolean NOT NULL,
    previous_high_contrast_scheme_value text,
    previous_high_contrast_scheme_problem text,
    has_previous_accent_color boolean NOT NULL,
    previous_accent_color_value text,
    previous_accent_color_problem text,
    has_previous_animations_enabled boolean NOT NULL,
    previous_animations_enabled_value boolean,
    previous_animations_enabled_problem text,
    has_previous_ui_effects boolean NOT NULL,
    previous_ui_effects_value boolean,
    previous_ui_effects_problem text,
    has_previous_menu_animation boolean NOT NULL,
    previous_menu_animation_value boolean,
    previous_menu_animation_problem text,
    has_previous_menu_fade boolean NOT NULL,
    previous_menu_fade_value boolean,
    previous_menu_fade_problem text,
    has_previous_combo_box_animation boolean NOT NULL,
    previous_combo_box_animation_value boolean,
    previous_combo_box_animation_problem text,
    has_previous_cursor_width boolean NOT NULL,
    previous_cursor_width_value double precision,
    previous_cursor_width_problem text,
    has_previous_cursor_height boolean NOT NULL,
    previous_cursor_height_value double precision,
    previous_cursor_height_problem text,
    has_previous_caret_width boolean NOT NULL,
    previous_caret_width_value bigint,
    previous_caret_width_problem text,
    has_previous_caret_blink_time boolean NOT NULL,
    previous_caret_blink_time_value bigint,
    previous_caret_blink_time_problem text,
    has_previous_focus_border_width boolean NOT NULL,
    previous_focus_border_width_value bigint,
    previous_focus_border_width_problem text,
    has_previous_focus_border_height boolean NOT NULL,
    previous_focus_border_height_value bigint,
    previous_focus_border_height_problem text,
    has_previous_keyboard_cues boolean NOT NULL,
    previous_keyboard_cues_value boolean,
    previous_keyboard_cues_problem text,
    has_previous_auto_hide_scroll_bars boolean NOT NULL,
    previous_auto_hide_scroll_bars_value boolean,
    previous_auto_hide_scroll_bars_problem text,
    has_previous_message_duration boolean NOT NULL,
    previous_message_duration_value bigint,
    previous_message_duration_problem text,
    has_previous_sticky_keys boolean NOT NULL,
    previous_sticky_keys_value boolean,
    previous_sticky_keys_problem text,
    has_previous_filter_keys boolean NOT NULL,
    previous_filter_keys_value boolean,
    previous_filter_keys_problem text,
    has_previous_toggle_keys boolean NOT NULL,
    previous_toggle_keys_value boolean,
    previous_toggle_keys_problem text,
    has_previous_mouse_keys boolean NOT NULL,
    previous_mouse_keys_value boolean,
    previous_mouse_keys_problem text,
    has_current_monitors boolean NOT NULL,
    has_current_monitors_value boolean,
    current_monitors_problem text,
    has_current_text_scale_factor boolean NOT NULL,
    current_text_scale_factor_value double precision,
    current_text_scale_factor_problem text,
    has_current_apps_use_light_theme boolean NOT NULL,
    current_apps_use_light_theme_value boolean,
    current_apps_use_light_theme_problem text,
    has_current_transparency_effects boolean NOT NULL,
    current_transparency_effects_value boolean,
    current_transparency_effects_problem text,
    has_current_color_filter_active boolean NOT NULL,
    current_color_filter_active_value boolean,
    current_color_filter_active_problem text,
    has_current_color_filter_type boolean NOT NULL,
    current_color_filter_type_value bigint,
    current_color_filter_type_problem text,
    has_current_high_contrast boolean NOT NULL,
    current_high_contrast_value boolean,
    current_high_contrast_problem text,
    has_current_high_contrast_scheme boolean NOT NULL,
    current_high_contrast_scheme_value text,
    current_high_contrast_scheme_problem text,
    has_current_accent_color boolean NOT NULL,
    current_accent_color_value text,
    current_accent_color_problem text,
    has_current_animations_enabled boolean NOT NULL,
    current_animations_enabled_value boolean,
    current_animations_enabled_problem text,
    has_current_ui_effects boolean NOT NULL,
    current_ui_effects_value boolean,
    current_ui_effects_problem text,
    has_current_menu_animation boolean NOT NULL,
    current_menu_animation_value boolean,
    current_menu_animation_problem text,
    has_current_menu_fade boolean NOT NULL,
    current_menu_fade_value boolean,
    current_menu_fade_problem text,
    has_current_combo_box_animation boolean NOT NULL,
    current_combo_box_animation_value boolean,
    current_combo_box_animation_problem text,
    has_current_cursor_width boolean NOT NULL,
    current_cursor_width_value double precision,
    current_cursor_width_problem text,
    has_current_cursor_height boolean NOT NULL,
    current_cursor_height_value double precision,
    current_cursor_height_problem text,
    has_current_caret_width boolean NOT NULL,
    current_caret_width_value bigint,
    current_caret_width_problem text,
    has_current_caret_blink_time boolean NOT NULL,
    current_caret_blink_time_value bigint,
    current_caret_blink_time_problem text,
    has_current_focus_border_width boolean NOT NULL,
    current_focus_border_width_value bigint,
    current_focus_border_width_problem text,
    has_current_focus_border_height boolean NOT NULL,
    current_focus_border_height_value bigint,
    current_focus_border_height_problem text,
    has_current_keyboard_cues boolean NOT NULL,
    current_keyboard_cues_value boolean,
    current_keyboard_cues_problem text,
    has_current_auto_hide_scroll_bars boolean NOT NULL,
    current_auto_hide_scroll_bars_value boolean,
    current_auto_hide_scroll_bars_problem text,
    has_current_message_duration boolean NOT NULL,
    current_message_duration_value bigint,
    current_message_duration_problem text,
    has_current_sticky_keys boolean NOT NULL,
    current_sticky_keys_value boolean,
    current_sticky_keys_problem text,
    has_current_filter_keys boolean NOT NULL,
    current_filter_keys_value boolean,
    current_filter_keys_problem text,
    has_current_toggle_keys boolean NOT NULL,
    current_toggle_keys_value boolean,
    current_toggle_keys_problem text,
    has_current_mouse_keys boolean NOT NULL,
    current_mouse_keys_value boolean,
    current_mouse_keys_problem text,
    notice_kind_name_id integer NOT NULL,
    notice_ui_action bigint,
    notice_area text,
    notice_source text,
    PRIMARY KEY (recording_id, event_key)
);

CREATE TABLE windows_preference_snapshot_monitors (
    recording_id uuid NOT NULL,
    owner_key bigint NOT NULL,
    ordinal_1 integer NOT NULL,
    device_name text NOT NULL,
    bounds_x integer NOT NULL,
    bounds_y integer NOT NULL,
    bounds_width integer NOT NULL,
    bounds_height integer NOT NULL,
    is_primary boolean NOT NULL,
    dpi_x bigint,
    dpi_y bigint,
    PRIMARY KEY (recording_id, owner_key, ordinal_1)
);

CREATE TABLE windows_preference_change_previous_monitors (
    recording_id uuid NOT NULL,
    owner_key bigint NOT NULL,
    ordinal_1 integer NOT NULL,
    device_name text NOT NULL,
    bounds_x integer NOT NULL,
    bounds_y integer NOT NULL,
    bounds_width integer NOT NULL,
    bounds_height integer NOT NULL,
    is_primary boolean NOT NULL,
    dpi_x bigint,
    dpi_y bigint,
    PRIMARY KEY (recording_id, owner_key, ordinal_1)
);

CREATE TABLE windows_preference_change_current_monitors (
    recording_id uuid NOT NULL,
    owner_key bigint NOT NULL,
    ordinal_1 integer NOT NULL,
    device_name text NOT NULL,
    bounds_x integer NOT NULL,
    bounds_y integer NOT NULL,
    bounds_width integer NOT NULL,
    bounds_height integer NOT NULL,
    is_primary boolean NOT NULL,
    dpi_x bigint,
    dpi_y bigint,
    PRIMARY KEY (recording_id, owner_key, ordinal_1)
);

INSERT INTO recording_tables (table_name, table_order)
    SELECT 'windows_preference_snapshots', max(table_order) + 1 FROM recording_tables;
INSERT INTO recording_tables (table_name, table_order)
    SELECT 'windows_preference_changes', max(table_order) + 1 FROM recording_tables;
INSERT INTO recording_tables (table_name, table_order)
    SELECT 'windows_preference_snapshot_monitors', max(table_order) + 1 FROM recording_tables;
INSERT INTO recording_tables (table_name, table_order)
    SELECT 'windows_preference_change_previous_monitors', max(table_order) + 1 FROM recording_tables;
INSERT INTO recording_tables (table_name, table_order)
    SELECT 'windows_preference_change_current_monitors', max(table_order) + 1 FROM recording_tables;

INSERT INTO recording_references (table_name, columns, referenced_table, referenced_columns)
VALUES
    ('windows_preference_snapshots', '{recording_id,event_key}', 'events', '{recording_id,event_key}'),
    ('windows_preference_snapshots', '{reason_name_id}', 'names', '{name_id}'),
    ('windows_preference_changes', '{recording_id,event_key}', 'events', '{recording_id,event_key}'),
    ('windows_preference_changes', '{setting_name_id}', 'names', '{name_id}'),
    ('windows_preference_changes', '{notice_kind_name_id}', 'names', '{name_id}'),
    ('windows_preference_snapshot_monitors', '{recording_id,owner_key}', 'windows_preference_snapshots', '{recording_id,event_key}'),
    ('windows_preference_change_previous_monitors', '{recording_id,owner_key}', 'windows_preference_changes', '{recording_id,event_key}'),
    ('windows_preference_change_current_monitors', '{recording_id,owner_key}', 'windows_preference_changes', '{recording_id,event_key}');
