-- The browser records of a recording's accessibility preferences, on the
-- browser.preferences channel (protocol 0.56): the listed browser
-- preferences of a profile as it finished loading (browser-preferences),
-- each change of one of them with its reading before and after
-- (browser-preference-changed), the preferences each page's view is sent
-- (web-preferences-sent), and each zoom level change (zoom-level-changed).
-- Each browser preference is stored as its value, by the preference's type,
-- whether that is the default, and the problem that stopped its reading;
-- the one text list, the sites without page colours, in a child table. The
-- evidence tables are not written for a recording that has a recording file
-- (see 0013_recording_files.sql); they keep mapping every payload member so
-- the database writer still accepts every record. See
-- docs/architecture/accessibility-preferences.md, "Stage 2".
--
-- Each table is made as 0009_unpartitioned_recording_tables.sql left the
-- other per-recording tables: an ordinary table keyed by recording and
-- event, whose references are listed in recording_references and checked
-- when the recording is completed, as since 0011_bulk_reference_checks.sql,
-- and not by a foreign key.

CREATE TABLE browser_preference_snapshots (
    recording_id uuid NOT NULL,
    event_key bigint NOT NULL,
    context_key bigint NOT NULL,
    profile_directory text NOT NULL,
    new_profile boolean NOT NULL,
    preferences_standard_font_family_value text,
    preferences_standard_font_family_is_default boolean,
    preferences_standard_font_family_problem text,
    preferences_fixed_font_family_value text,
    preferences_fixed_font_family_is_default boolean,
    preferences_fixed_font_family_problem text,
    preferences_serif_font_family_value text,
    preferences_serif_font_family_is_default boolean,
    preferences_serif_font_family_problem text,
    preferences_sans_serif_font_family_value text,
    preferences_sans_serif_font_family_is_default boolean,
    preferences_sans_serif_font_family_problem text,
    preferences_cursive_font_family_value text,
    preferences_cursive_font_family_is_default boolean,
    preferences_cursive_font_family_problem text,
    preferences_fantasy_font_family_value text,
    preferences_fantasy_font_family_is_default boolean,
    preferences_fantasy_font_family_problem text,
    preferences_math_font_family_value text,
    preferences_math_font_family_is_default boolean,
    preferences_math_font_family_problem text,
    preferences_default_font_size_value bigint,
    preferences_default_font_size_is_default boolean,
    preferences_default_font_size_problem text,
    preferences_default_fixed_font_size_value bigint,
    preferences_default_fixed_font_size_is_default boolean,
    preferences_default_fixed_font_size_problem text,
    preferences_minimum_font_size_value bigint,
    preferences_minimum_font_size_is_default boolean,
    preferences_minimum_font_size_problem text,
    preferences_minimum_logical_font_size_value bigint,
    preferences_minimum_logical_font_size_is_default boolean,
    preferences_minimum_logical_font_size_problem text,
    preferences_color_scheme_value bigint,
    preferences_color_scheme_is_default boolean,
    preferences_color_scheme_problem text,
    preferences_focus_highlight_value boolean,
    preferences_focus_highlight_is_default boolean,
    preferences_focus_highlight_problem text,
    preferences_requested_page_colors_value bigint,
    preferences_requested_page_colors_is_default boolean,
    preferences_requested_page_colors_problem text,
    preferences_page_colors_only_on_increased_contrast_value boolean,
    preferences_page_colors_only_on_increased_contrast_is_default boolean,
    preferences_page_colors_only_on_increased_contrast_problem text,
    has_preferences_page_colors_block_list_value boolean NOT NULL,
    preferences_page_colors_block_list_is_default boolean,
    preferences_page_colors_block_list_problem text,
    preferences_caret_browsing_value boolean,
    preferences_caret_browsing_is_default boolean,
    preferences_caret_browsing_problem text,
    PRIMARY KEY (recording_id, event_key)
);

CREATE TABLE browser_preference_changes (
    recording_id uuid NOT NULL,
    event_key bigint NOT NULL,
    context_key bigint NOT NULL,
    profile_directory text NOT NULL,
    preference_name_id integer NOT NULL,
    has_previous_standard_font_family boolean NOT NULL,
    previous_standard_font_family_value text,
    previous_standard_font_family_is_default boolean,
    previous_standard_font_family_problem text,
    has_previous_fixed_font_family boolean NOT NULL,
    previous_fixed_font_family_value text,
    previous_fixed_font_family_is_default boolean,
    previous_fixed_font_family_problem text,
    has_previous_serif_font_family boolean NOT NULL,
    previous_serif_font_family_value text,
    previous_serif_font_family_is_default boolean,
    previous_serif_font_family_problem text,
    has_previous_sans_serif_font_family boolean NOT NULL,
    previous_sans_serif_font_family_value text,
    previous_sans_serif_font_family_is_default boolean,
    previous_sans_serif_font_family_problem text,
    has_previous_cursive_font_family boolean NOT NULL,
    previous_cursive_font_family_value text,
    previous_cursive_font_family_is_default boolean,
    previous_cursive_font_family_problem text,
    has_previous_fantasy_font_family boolean NOT NULL,
    previous_fantasy_font_family_value text,
    previous_fantasy_font_family_is_default boolean,
    previous_fantasy_font_family_problem text,
    has_previous_math_font_family boolean NOT NULL,
    previous_math_font_family_value text,
    previous_math_font_family_is_default boolean,
    previous_math_font_family_problem text,
    has_previous_default_font_size boolean NOT NULL,
    previous_default_font_size_value bigint,
    previous_default_font_size_is_default boolean,
    previous_default_font_size_problem text,
    has_previous_default_fixed_font_size boolean NOT NULL,
    previous_default_fixed_font_size_value bigint,
    previous_default_fixed_font_size_is_default boolean,
    previous_default_fixed_font_size_problem text,
    has_previous_minimum_font_size boolean NOT NULL,
    previous_minimum_font_size_value bigint,
    previous_minimum_font_size_is_default boolean,
    previous_minimum_font_size_problem text,
    has_previous_minimum_logical_font_size boolean NOT NULL,
    previous_minimum_logical_font_size_value bigint,
    previous_minimum_logical_font_size_is_default boolean,
    previous_minimum_logical_font_size_problem text,
    has_previous_color_scheme boolean NOT NULL,
    previous_color_scheme_value bigint,
    previous_color_scheme_is_default boolean,
    previous_color_scheme_problem text,
    has_previous_focus_highlight boolean NOT NULL,
    previous_focus_highlight_value boolean,
    previous_focus_highlight_is_default boolean,
    previous_focus_highlight_problem text,
    has_previous_requested_page_colors boolean NOT NULL,
    previous_requested_page_colors_value bigint,
    previous_requested_page_colors_is_default boolean,
    previous_requested_page_colors_problem text,
    has_previous_page_colors_only_on_increased_contrast boolean NOT NULL,
    previous_page_colors_only_on_increased_contrast_value boolean,
    previous_page_colors_only_on_increased_contrast_is_default boolean,
    previous_page_colors_only_on_increased_contrast_problem text,
    has_previous_page_colors_block_list boolean NOT NULL,
    has_previous_page_colors_block_list_value boolean,
    previous_page_colors_block_list_is_default boolean,
    previous_page_colors_block_list_problem text,
    has_previous_caret_browsing boolean NOT NULL,
    previous_caret_browsing_value boolean,
    previous_caret_browsing_is_default boolean,
    previous_caret_browsing_problem text,
    has_current_standard_font_family boolean NOT NULL,
    current_standard_font_family_value text,
    current_standard_font_family_is_default boolean,
    current_standard_font_family_problem text,
    has_current_fixed_font_family boolean NOT NULL,
    current_fixed_font_family_value text,
    current_fixed_font_family_is_default boolean,
    current_fixed_font_family_problem text,
    has_current_serif_font_family boolean NOT NULL,
    current_serif_font_family_value text,
    current_serif_font_family_is_default boolean,
    current_serif_font_family_problem text,
    has_current_sans_serif_font_family boolean NOT NULL,
    current_sans_serif_font_family_value text,
    current_sans_serif_font_family_is_default boolean,
    current_sans_serif_font_family_problem text,
    has_current_cursive_font_family boolean NOT NULL,
    current_cursive_font_family_value text,
    current_cursive_font_family_is_default boolean,
    current_cursive_font_family_problem text,
    has_current_fantasy_font_family boolean NOT NULL,
    current_fantasy_font_family_value text,
    current_fantasy_font_family_is_default boolean,
    current_fantasy_font_family_problem text,
    has_current_math_font_family boolean NOT NULL,
    current_math_font_family_value text,
    current_math_font_family_is_default boolean,
    current_math_font_family_problem text,
    has_current_default_font_size boolean NOT NULL,
    current_default_font_size_value bigint,
    current_default_font_size_is_default boolean,
    current_default_font_size_problem text,
    has_current_default_fixed_font_size boolean NOT NULL,
    current_default_fixed_font_size_value bigint,
    current_default_fixed_font_size_is_default boolean,
    current_default_fixed_font_size_problem text,
    has_current_minimum_font_size boolean NOT NULL,
    current_minimum_font_size_value bigint,
    current_minimum_font_size_is_default boolean,
    current_minimum_font_size_problem text,
    has_current_minimum_logical_font_size boolean NOT NULL,
    current_minimum_logical_font_size_value bigint,
    current_minimum_logical_font_size_is_default boolean,
    current_minimum_logical_font_size_problem text,
    has_current_color_scheme boolean NOT NULL,
    current_color_scheme_value bigint,
    current_color_scheme_is_default boolean,
    current_color_scheme_problem text,
    has_current_focus_highlight boolean NOT NULL,
    current_focus_highlight_value boolean,
    current_focus_highlight_is_default boolean,
    current_focus_highlight_problem text,
    has_current_requested_page_colors boolean NOT NULL,
    current_requested_page_colors_value bigint,
    current_requested_page_colors_is_default boolean,
    current_requested_page_colors_problem text,
    has_current_page_colors_only_on_increased_contrast boolean NOT NULL,
    current_page_colors_only_on_increased_contrast_value boolean,
    current_page_colors_only_on_increased_contrast_is_default boolean,
    current_page_colors_only_on_increased_contrast_problem text,
    has_current_page_colors_block_list boolean NOT NULL,
    has_current_page_colors_block_list_value boolean,
    current_page_colors_block_list_is_default boolean,
    current_page_colors_block_list_problem text,
    has_current_caret_browsing boolean NOT NULL,
    current_caret_browsing_value boolean,
    current_caret_browsing_is_default boolean,
    current_caret_browsing_problem text,
    PRIMARY KEY (recording_id, event_key)
);

CREATE TABLE browser_web_preferences_sent (
    recording_id uuid NOT NULL,
    event_key bigint NOT NULL,
    context_key bigint NOT NULL,
    page_frame_tree_node_id integer NOT NULL,
    primary_page boolean NOT NULL,
    renderer_process_id integer NOT NULL,
    view_id text NOT NULL,
    point_name_id integer NOT NULL,
    first boolean NOT NULL,
    fields_standard_font_family text,
    fields_fixed_font_family text,
    fields_serif_font_family text,
    fields_sans_serif_font_family text,
    fields_cursive_font_family text,
    fields_fantasy_font_family text,
    fields_math_font_family text,
    fields_default_font_size bigint,
    fields_default_fixed_font_size bigint,
    fields_minimum_font_size bigint,
    fields_minimum_logical_font_size bigint,
    fields_prefers_reduced_motion boolean,
    fields_prefers_reduced_transparency boolean,
    fields_inverted_colors boolean,
    fields_text_track_text_size text,
    fields_text_track_font_family text,
    fields_in_forced_colors boolean,
    fields_is_forced_colors_disabled boolean,
    fields_preferred_root_scrollbar_color_scheme text,
    fields_preferred_color_scheme text,
    fields_preferred_contrast text,
    fields_focus_ring_color text,
    fields_has_caret_blink_interval boolean,
    fields_caret_blink_interval_milliseconds double precision,
    fields_caret_browsing_enabled boolean,
    fields_use_overlay_scrollbar boolean,
    fields_caption_font_family text,
    fields_caption_font_height bigint,
    fields_small_caption_font_family text,
    fields_small_caption_font_height bigint,
    fields_menu_font_family text,
    fields_menu_font_height bigint,
    fields_status_font_family text,
    fields_status_font_height bigint,
    fields_message_font_family text,
    fields_message_font_height bigint,
    PRIMARY KEY (recording_id, event_key)
);

CREATE TABLE browser_zoom_level_changes (
    recording_id uuid NOT NULL,
    event_key bigint NOT NULL,
    context_key bigint NOT NULL,
    mode_name_id integer NOT NULL,
    follows_default boolean NOT NULL,
    host text NOT NULL,
    scheme text NOT NULL,
    zoom_level double precision NOT NULL,
    zoom_percent double precision NOT NULL,
    PRIMARY KEY (recording_id, event_key)
);

CREATE TABLE browser_preference_snapshot_text_lists (
    recording_id uuid NOT NULL,
    owner_key bigint NOT NULL,
    ordinal_1 integer NOT NULL,
    value text NOT NULL,
    PRIMARY KEY (recording_id, owner_key, ordinal_1)
);

CREATE TABLE browser_preference_change_previous_text_lists (
    recording_id uuid NOT NULL,
    owner_key bigint NOT NULL,
    ordinal_1 integer NOT NULL,
    value text NOT NULL,
    PRIMARY KEY (recording_id, owner_key, ordinal_1)
);

CREATE TABLE browser_preference_change_current_text_lists (
    recording_id uuid NOT NULL,
    owner_key bigint NOT NULL,
    ordinal_1 integer NOT NULL,
    value text NOT NULL,
    PRIMARY KEY (recording_id, owner_key, ordinal_1)
);

INSERT INTO recording_tables (table_name, table_order)
    SELECT 'browser_preference_snapshots', max(table_order) + 1 FROM recording_tables;
INSERT INTO recording_tables (table_name, table_order)
    SELECT 'browser_preference_changes', max(table_order) + 1 FROM recording_tables;
INSERT INTO recording_tables (table_name, table_order)
    SELECT 'browser_web_preferences_sent', max(table_order) + 1 FROM recording_tables;
INSERT INTO recording_tables (table_name, table_order)
    SELECT 'browser_zoom_level_changes', max(table_order) + 1 FROM recording_tables;
INSERT INTO recording_tables (table_name, table_order)
    SELECT 'browser_preference_snapshot_text_lists', max(table_order) + 1 FROM recording_tables;
INSERT INTO recording_tables (table_name, table_order)
    SELECT 'browser_preference_change_previous_text_lists', max(table_order) + 1 FROM recording_tables;
INSERT INTO recording_tables (table_name, table_order)
    SELECT 'browser_preference_change_current_text_lists', max(table_order) + 1 FROM recording_tables;

INSERT INTO recording_references (table_name, columns, referenced_table, referenced_columns)
VALUES
    ('browser_preference_snapshots', '{recording_id,event_key}', 'events', '{recording_id,event_key}'),
    ('browser_preference_snapshots', '{recording_id,context_key}', 'browser_contexts', '{recording_id,identity_key}'),
    ('browser_preference_changes', '{recording_id,event_key}', 'events', '{recording_id,event_key}'),
    ('browser_preference_changes', '{recording_id,context_key}', 'browser_contexts', '{recording_id,identity_key}'),
    ('browser_preference_changes', '{preference_name_id}', 'names', '{name_id}'),
    ('browser_web_preferences_sent', '{recording_id,event_key}', 'events', '{recording_id,event_key}'),
    ('browser_web_preferences_sent', '{recording_id,context_key}', 'browser_contexts', '{recording_id,identity_key}'),
    ('browser_web_preferences_sent', '{point_name_id}', 'names', '{name_id}'),
    ('browser_zoom_level_changes', '{recording_id,event_key}', 'events', '{recording_id,event_key}'),
    ('browser_zoom_level_changes', '{recording_id,context_key}', 'browser_contexts', '{recording_id,identity_key}'),
    ('browser_zoom_level_changes', '{mode_name_id}', 'names', '{name_id}'),
    ('browser_preference_snapshot_text_lists', '{recording_id,owner_key}', 'browser_preference_snapshots', '{recording_id,event_key}'),
    ('browser_preference_change_previous_text_lists', '{recording_id,owner_key}', 'browser_preference_changes', '{recording_id,event_key}'),
    ('browser_preference_change_current_text_lists', '{recording_id,owner_key}', 'browser_preference_changes', '{recording_id,event_key}');
