<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../Recorder.Contracts/Recorder.Contracts.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="System.IO.Pipes.AccessControl" Version="5.0.0" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Recorder.Tests" />
  </ItemGroup>
</Project>
