<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Recorder.Coordinator/Recorder.Coordinator.csproj" />
    <ProjectReference Include="../Recorder.WindowsCapture/Recorder.WindowsCapture.csproj" />
  </ItemGroup>
</Project>
