assert(is_win)

component("recorder_bridge") {
  defines = [ "IS_RECORDER_BRIDGE_IMPL" ]

  sources = [
    "browser_bridge.cc",
    "browser_bridge.h",
    "cookie_text.cc",
    "cookie_text.h",
    "recorder_protocol.cc",
    "recorder_protocol.h",
    "recorder_switches.h",
  ]

  deps = [
    "//base",
    "//components/version_info",
  ]
}
